= Chap6 Storage
:image-url1: https://cdn.jsdelivr.net/gh/jeon3029/learning_container@master/kube/img/img6_1.png
:image-url2: https://cdn.jsdelivr.net/gh/jeon3029/learning_container@master/kube/img/img6_2.png
:image-url3: https://cdn.jsdelivr.net/gh/jeon3029/learning_container@master/kube/img/img6_3.png
:image-url4: https://cdn.jsdelivr.net/gh/jeon3029/learning_container@master/kube/img/img6_4.png


* Kubernetes Volume은 파드의 구성 요소로 컨테이너와 동일하게 파드 스펙에서 정의
* Volume 는 각 파드의 모든 컨테이너에서 사용ㅇ 가능하지만 접근하려는 컨테이너에서 각각 마운트 돼야 함.

image::{image-url1}[width=300]

== 사용 가능한 볼륨 유형

====
.emptyDir: 
일시적인 데이터를 저장하는 데 사용되는 간단한 빈 디렉터리

.hostPath: 
워커 노드의 파일시스템을 파드의 디렉터리로 마운트하는 데 사용

.gitRepo: 
깃 리포지터리의 콘텐츠를 체크아웃해 초기화한 볼륨

.nfs: 
NFS 공유를 파드에 마운트한다.

.gcePersistentDisk(Google Compute Engin Persistent Disk), awsElasticBlockStore, azureDisk(Microsoft Azure Disk Volume):
클라우드 제공자의 전용 스토리지를 마운트하는 데 사용

.cinder, cephfs, iscsi, flocker, glusterfs, quobyte, rbd, flexVolume, vsphere Volume, photonPersistentDisk, scaleIO: 
다른 유형의 네트워크 스토리지를 마운트하는 데 사용

.configMap, secret, downwardAPI: 
Kubernetes 리소스나 클러스터 정보를 파드에 노출하는 데 사용

.persistentVolumeClaim: 
사전에 혹은 동적으로 프로비저닝된 퍼시스턴트 스토리지를 사용
====

== emptyDir 

파드가 삭제되면 볼륨의 콘텐츠는 사라진다
동일 파드에서 실행 중인 컨테이너 간 파일을 공유


. 컨테이너간의 소통 가능 
[source,yaml]
----
apiVersion: v1
kind: Pod
metadata:
  name: fortune
spec:
  containers:
  - image: luksa/fortune
    name: html-generator
    volumeMounts:
    - name: html
      mountPath: /var/htdocs
  - image: nginx:alpine
    name: web-server
    volumeMounts:
    - name: html
      mountPath: /usr/share/nginx/html
      readOnly: true
    ports:
    - containerPort: 80
      protocol: TCP
  volumes:
  - name: html
    emptyDir: {}
----


== git repo

emptyDir 와 같은나 컨텐츠가 채워져 있음

깃 리포지터리에 추가 커밋을 푸시해도 볼륨에 있는 파일은 변경되지 않는다

새 버전을 보려면 파드를 삭제하고 다시 생성해야 한다
-> 변경 사항이 있을 때마다 파드를 삭제하는 대신에 볼륨이 항상 깃 리포지터리와 동기화하도록 추가 프로세스

== hostPath

노드 파일시스템의 파일 접근
-> 파드가 다른 노드로 다시 스케줄링되면 더 이상 이전 데이터를 볼 수 없다
hostPath 볼륨의 콘텐츠는 삭제되지 않는다.

== 퍼시스턴트 스토리지

. nfs volume
[source,yaml]
----
volumes:
  - name: mongodb-data
    nfs:
      server: 1.2.3.4
      path: /some/path
----

== 퍼시스턴트볼륨(PV)과 퍼시스턴트볼륨클레임(PVC) 

애플리케이션을 배포하는 개발자는 기저에 어떤 종류의 스토리지 기술이 사용되는지 알 필요가 없음
인프라스트럭처 관련 처리는 클러스터 관리자만의 영역
-> 퍼시스턴트볼륨과 퍼시스턴트볼륨클레임을 사용해 파드와 스토리지 인프라스트럭처를 분리

image::{image-url2}[]

=== PV 생성

[source,yaml]
----
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongodb-pv
spec:
  capacity: 
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
    - ReadOnlyMany
  persistentVolumeReclaimPolicy: Retain
  # 클레임이 해제된 후 퍼시스턴트볼륨은 유지
  # 리클레임 정책은 Recycle과 Delete
  gcePersistentDisk:
    pdName: mongodb
    fsType: ext4

----
image::{image-url3}[]

== PVC 생성

[source,yaml]
----
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb-pvc 
spec:
  storageClassName: fast
  resources:
    requests:
      storage: 100Mi
  accessModes:
    - ReadWriteOnce
----

====
RWO(ReadWriteOnce): 단일 노드만이 읽기/쓰기용으로 볼륨을 마운트할 수 있다.

ROX(ReadOnlyMany): 다수 노드가 읽기용으로 볼륨을 마운트 할 수 있다.

RWX(ReadWriteMany): 다수 노드가 읽기/쓰기용으로 볼륨을 마운트할 수 있다.
====

=== pod 에서 PVC 사용

[source,yaml]
----
apiVersion: v1
kind: Pod
metadata:
  name: mongodb 
spec:
  containers:
  - image: mongo
    name: mongodb
    volumeMounts:
    - name: mongodb-data
      mountPath: /data/db
    ports:
    - containerPort: 27017
      protocol: TCP
  volumes:
  - name: mongodb-data
    persistentVolumeClaim:
      claimName: mongodb-pvc
----

.PV,PVC 통해 volume 로드하는 경우와의 차이점
image::{image-url4}[]