= 03.Kubernetes
:reproducible:
:listing-caption: Source
:source-highlighter: rouge
:rouge-style: monokai
:toc:
:hardbreaks:
:sourcedir: ./book/ch3/

// :image-url1: https://cdn.jsdelivr.net/gh/jeon3029/learning_container@master/infra/img/img3_1.png

컨테이터 인프라 환경::
리눅스 운영체제의 커널 하나에서 여러개의 컨테이너가 격리된 상태로 실행되는 인프라 환경

* 눈송이서버 방지
* 가상화 환경에서는 각각 가상머신이 모두 독립 운영체제커널 가지는데 반해 컨테이너는 OS 커널 하나에 여러개가 격리된 형태로 실행 됨

구글이 Borg 를 기반으로한 Kubernetes 를 오픈소스화 하면서 인프라 환경을 효율적으로 관리 할 수 있게 됨. -> 사실상 인프라 관리기술의 표준 기술

== 3.1 쿠버네티스 이해하기

Kubernetes 는 컨테이너 오케스트레이션을 위한 솔루션

* 복잡한 단계를 관리하고 요소들의 유기적인 관계를 미리 정의하여 손쉽게 사용하도록 서비스를 제공

.기타 orchestration 기술 들
. 도커 스웜(Doker Swarm)
. 메소스(Meses)
. 노매드(Nomad)
. 쿠버네티스(Kubernetes)
.. 컨테이너 오케스트레이션을 한다면 k8s 를 우선적으로 고려

=== k8s 구성 방법

. 퍼플릭 클라우드 업체 관리형 k8s 사용(EKS, AKS, GKE)
. 설치형 k8s 사용(Rancher, OpenShift)
.. 유료임
. k8s 클러스터 자동 구성 솔루션 사용(kubeadm, kops, KRIB, kubespray)
.. 책에서는 `kubeadmin` 을 사용하여 구성
.. 설치되는 환경을 `Vagrant` 로 자동화하여 테스트 환경을 재구성 할 수 있게 함

=== k8s 구성하기

.3.1.3 Vagrantfile
[source,sh]
----
include::{sourcedir}3.1.3/Vagrantfile[]
----

.3.1.3 config.sh
[source,sh]
----
include::{sourcedir}3.1.3/config.sh[]
----

.3.1.3 install_pkg.sh
[source,sh]
----
include::{sourcedir}3.1.3/install_pkg.sh[]
----

.3.1.3 master_node.sh
[source,sh]
----
include::{sourcedir}3.1.3/master_node.sh[]
----

.3.1.3 work_nodes.sh
[source,sh]
----
include::{sourcedir}3.1.3/work_nodes.sh[]
----

.3.1.3 실행결과
[source,sh]
----
[root@m-k8s ~]# kubectl get nodes
NAME     STATUS   ROLES    AGE     VERSION
m-k8s    Ready    master   11m     v1.18.4
w1-k8s   Ready    <none>   8m35s   v1.18.4
w2-k8s   Ready    <none>   5m23s   v1.18.4
w3-k8s   Ready    <none>   99s     v1.18.4

[root@m-k8s ~]# kubectl get pods --all-namespaces | grep proxy
kube-system   kube-proxy-8mnmx                          1/1     Running   0          13m
kube-system   kube-proxy-bsl7k                          1/1     Running   0          11m
kube-system   kube-proxy-dv2wn                          1/1     Running   0          4m10s
kube-system   kube-proxy-nkqh8                          1/1     Running   0          7m54s
[root@m-k8s ~]# kubectl get pods --all-namespaces | grep core
kube-system   coredns-66bff467f8-gnq59                  1/1     Running   0          14m
kube-system   coredns-66bff467f8-p9t7t                  1/1     Running   0          14m
----

=== kubectl

kubectl 은 꼭 마스터 노드에 위치할 필요는 없음
[source,sh]
----
[root@w3-k8s ~]# hostname
w3-k8s
[root@w3-k8s ~]# kubectl get nodes
The connection to the server localhost:8080 was refused - did you specify the right host or port?
[root@w3-k8s ~]# scp root@192.168.1.10:/etc/kubernetes/admin.conf .
The authenticity of host '192.168.1.10 (192.168.1.10)' can't be established.
ECDSA key fingerprint is SHA256:l6XikZFgOibzSygqZ6+UYHUnEmjFEFhx7PpZw0I3WaM.
ECDSA key fingerprint is MD5:09:74:43:ef:38:3e:36:a1:7e:51:76:1a:ac:2d:7e:0c.
Are you sure you want to continue connecting (yes/no)? yes
Warning: Permanently added '192.168.1.10' (ECDSA) to the list of known hosts.
root@192.168.1.10's password: 
admin.conf                                                                                      100% 5452     2.0MB/s   00:00    
See 'kubectl get --help' for usage.
[root@w3-k8s ~]# kubectl get nodes --kubeconfig admin.conf
NAME     STATUS   ROLES    AGE     VERSION
m-k8s    Ready    master   19m     v1.18.4
w1-k8s   Ready    <none>   16m     v1.18.4
w2-k8s   Ready    <none>   13m     v1.18.4
w3-k8s   Ready    <none>   9m46s   v1.18.4
[root@w3-k8s ~]# 
----

API 서버의 접속정보를 가져와서 nodes 의 위치를 파악하도록 함.


=== kubelet

파드의 생성과 상태관리, 복구 등을 담당하는 매우 중요한 요소

.3.1.6/nginx-pod.yaml
[source,sh]
----
include::{sourcedir}3.1.6/nginx-pod.yaml[]
----

.3.1.6/pods 생성
[source,sh]
----
[root@m-k8s ~]# kubectl create -f ~/_Book_k8sInfra/ch3/3.1.6/nginx-pod.yaml 
pod/nginx-pod created
[root@m-k8s ~]# kubectl get pod
NAME        READY   STATUS              RESTARTS   AGE
nginx-pod   0/1     ContainerCreating   0          8s
[root@m-k8s ~]# kubectl get pods -o wide
NAME        READY   STATUS              RESTARTS   AGE   IP       NODE     NOMINATED NODE   READINESS GATES
nginx-pod   0/1     ContainerCreating   0          18s   <none>   w2-k8s   <none>           <none>
[root@m-k8s ~]# systemctl stop kubelet
[root@m-k8s ~]# kubectl get pod
NAME        READY   STATUS    RESTARTS   AGE
nginx-pod   1/1     Running   0          3m40s
[root@m-k8s ~]# kubectl delete pod nginx-pod
pod "nginx-pod" deleted
^C
[root@m-k8s ~]# kubectl get pod
NAME        READY   STATUS        RESTARTS   AGE
nginx-pod   0/1     Terminating   0          4m10s
[root@m-k8s ~]# systemctl start kubelet
[root@m-k8s ~]# kubectl get pod
No resources found in default namespace.
----

kubelet 에 문제가 생기면 pods 가 제대로 관리되지 않음

=== kube-proxy

파드의 통신을 담당. 



== 3.2 쿠버네티스 기본 사용법 배우기

== 3.3 쿠버네티스 연결을 담당하는 서비스


== 3.4 알아두면 쓸모 있는 쿠버네티스 오브젝트





== References

image:https://img.shields.io/badge/-Reference%20github-black?style=flat-square&logo=github&link=https://github.com/sysnet4admin/_Book_k8sInfra[github-li] https://github.com/sysnet4admin/_Book_k8sInfra[컨테이너 인프라 환경 구축을 위한 쿠버네티스/도커]
